// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/blukers/CandidateDetail.tsx": () => import("../components/mockups/blukers/CandidateDetail.tsx"),
  "./components/mockups/blukers/Candidates.tsx": () => import("../components/mockups/blukers/Candidates.tsx"),
  "./components/mockups/blukers/Dashboard.tsx": () => import("../components/mockups/blukers/Dashboard.tsx"),
  "./components/mockups/blukers/JobDetail.tsx": () => import("../components/mockups/blukers/JobDetail.tsx"),
  "./components/mockups/blukers/Jobs.tsx": () => import("../components/mockups/blukers/Jobs.tsx"),
  "./components/mockups/blukers/Pipeline.tsx": () => import("../components/mockups/blukers/Pipeline.tsx")
};
